### ISSUE TITLE
DATA source

### ISSUE THREAD

**Issue by FIsherYY** [SMU-CATCO/SmartCADD#2]
Where is alert_collection.csv and smi dataset

**Comment by FIsherYY** [comment]
how can i download attentive_fp_model_params.pt？

**Comment by YingxiuFan** [comment]
> how can i download attentive_fp_model_params.pt？
https://github.com/OpenDrugAI/AttentiveFP
Try this model , the output file is  ***.pt

**Comment by YingxiuFan** [comment]
> Where is alert_collection.csv and smi dataset
smi dataset may from ZINC dataset.
Where is alert_collection.csv
I Need help , too.

**Comment by elilaird** [comment]
Hi all, 

I have added the example data files in the `examples/example_data` directory.

**Comment by elilaird** [comment]
Now that the data is added I'm closing this issue.
